/*
 * Copyright (C) 2019 allen
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

var data = [
  {
    rank: 1,
    teamNumber: 1549,
    school: "American University A",
    tpr: 29.45,
    regional: "",
    orcs: "Richmond",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.153932293,
    cost: 1.153932293
  },
  {
    rank: 2,
    teamNumber: 1070,
    school: "Arizona State University A",
    tpr: 16.25,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.7369070309,
    cost: 0.7369070309
  },
  {
    rank: 3,
    teamNumber: 1054,
    school: "Auburn University A",
    tpr: 8.75,
    regional: "Jackson",
    orcs: "Decatur",
    regionalWins: 5,
    regionalTies: 1,
    regionalCS: 11,
    extraBidsEarned: 0,
    winCSPoints: 4.640625,
    tprPoints: 0.4274477642,
    cost: 5.068072764
  },
  {
    rank: 4,
    teamNumber: 1115,
    school: "Baylor University A",
    tpr: 23.75,
    regional: "",
    orcs: "Memphis",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.9938205765,
    cost: 0.9938205765
  },
  {
    rank: 5,
    teamNumber: 1205,
    school: "Bowdoin College A",
    tpr: 7,
    regional: "New Haven",
    orcs: "Chestnut Hill",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 17,
    extraBidsEarned: 0,
    winCSPoints: 7.21875,
    tprPoints: 0.3476798565,
    cost: 7.566429857
  },
  {
    rank: 6,
    teamNumber: 1489,
    school: "Brown University A",
    tpr: 27.75,
    regional: "New Rochelle",
    orcs: "Chestnut Hill",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 10.5,
    extraBidsEarned: 0,
    winCSPoints: 6.625,
    tprPoints: 1.109355773,
    cost: 7.734355773
  },
  {
    rank: 7,
    teamNumber: 1490,
    school: "Brown University B",
    tpr: 9,
    regional: "New Haven",
    orcs: "Chestnut Hill",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 16,
    extraBidsEarned: 0,
    winCSPoints: 6.5,
    tprPoints: 0.438609643,
    cost: 6.938609643
  },
  {
    rank: 8,
    teamNumber: 1335,
    school: "Colby College A",
    tpr: 0,
    regional: "New Haven",
    orcs: "Chestnut Hill",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 14.5,
    extraBidsEarned: 0,
    winCSPoints: 5.71875,
    tprPoints: 0,
    cost: 5.71875
  },
  {
    rank: 9,
    teamNumber: 1065,
    school: "College of William & Mary A",
    tpr: 19,
    regional: "",
    orcs: "Richmond",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.8372098063,
    cost: 0.8372098063
  },
  {
    rank: 10,
    teamNumber: 1268,
    school: "Columbia University A",
    tpr: 35.3,
    regional: "State College",
    orcs: "Central Islip",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 12.5,
    extraBidsEarned: 0,
    winCSPoints: 6.234375,
    tprPoints: 1.286698515,
    cost: 7.521073515
  },
  {
    rank: 11,
    teamNumber: 1269,
    school: "Columbia University B",
    tpr: 14.25,
    regional: "State College",
    orcs: "Central Islip",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 19,
    extraBidsEarned: 0,
    winCSPoints: 5.46875,
    tprPoints: 0.6595223636,
    cost: 6.128272364
  },
  {
    rank: 12,
    teamNumber: 1428,
    school: "Cornell College A",
    tpr: 19.55,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 7,
    regionalTies: 1,
    regionalCS: 8.5,
    extraBidsEarned: 1,
    winCSPoints: 5.7421875,
    tprPoints: 0.8564226238,
    cost: 7.258471136
  },
  {
    rank: 13,
    teamNumber: 1429,
    school: "Cornell College B",
    tpr: 4,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 18,
    extraBidsEarned: 1,
    winCSPoints: 6.375,
    tprPoints: 0.2042790806,
    cost: 7.237206989
  },
  {
    rank: 14,
    teamNumber: 1029,
    school: "Cornell University A",
    tpr: 40.86,
    regional: "",
    orcs: "Central Islip",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.383252235,
    cost: 1.383252235
  },
  {
    rank: 15,
    teamNumber: 1096,
    school: "Creighton University A",
    tpr: 0.75,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 6.78125,
    tprPoints: 0.03944081824,
    cost: 6.820690818
  },
  {
    rank: 16,
    teamNumber: 1530,
    school: "Duke University A",
    tpr: 26.6,
    regional: "Columbia",
    orcs: "Decatur",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 20,
    extraBidsEarned: 1,
    winCSPoints: 7.3125,
    tprPoints: 1.077670236,
    cost: 9.229187259
  },
  {
    rank: 17,
    teamNumber: 1531,
    school: "Duke University B",
    tpr: 23,
    regional: "Chapel Hill",
    orcs: "Decatur",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 17.5,
    extraBidsEarned: 1,
    winCSPoints: 6.28125,
    tprPoints: 0.9704937794,
    cost: 7.976918157
  },
  {
    rank: 18,
    teamNumber: 1272,
    school: "Eastern Michigan University A",
    tpr: 9.25,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 17,
    extraBidsEarned: 0,
    winCSPoints: 7.21875,
    tprPoints: 0.4497131377,
    cost: 7.668463138
  },
  {
    rank: 19,
    teamNumber: 1521,
    school: "Emory University A",
    tpr: 36,
    regional: "",
    orcs: "Decatur",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.300443542,
    cost: 1.300443542
  },
  {
    rank: 20,
    teamNumber: 1380,
    school: "Florida State University A",
    tpr: 21.4,
    regional: "",
    orcs: "Decatur",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.9189737508,
    cost: 0.9189737508
  },
  {
    rank: 21,
    teamNumber: 1381,
    school: "Florida State University B",
    tpr: 1,
    regional: "",
    orcs: "Decatur",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.05247098939,
    cost: 0.05247098939
  },
  {
    rank: 22,
    teamNumber: 1110,
    school: "George Washington University A",
    tpr: 19.5,
    regional: "",
    orcs: "Richmond",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.8546876808,
    cost: 0.8546876808
  },
  {
    rank: 23,
    teamNumber: 1328,
    school: "Georgetown University A",
    tpr: 22,
    regional: "Chapel Hill",
    orcs: "Richmond",
    regionalWins: 7,
    regionalTies: 1,
    regionalCS: 14.5,
    extraBidsEarned: 0,
    winCSPoints: 7.1484375,
    tprPoints: 0.9385740053,
    cost: 8.087011505
  },
  {
    rank: 24,
    teamNumber: 1329,
    school: "Georgetown University B",
    tpr: 18,
    regional: "Williamsburg",
    orcs: "Richmond",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 5.8125,
    tprPoints: 0.8015534477,
    cost: 6.614053448
  },
  {
    rank: 25,
    teamNumber: 1569,
    school: "Georgia Tech A",
    tpr: 46.93,
    regional: "",
    orcs: "Decatur",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.455689898,
    cost: 1.455689898
  },
  {
    rank: 26,
    teamNumber: 1570,
    school: "Georgia Tech B",
    tpr: 11.75,
    regional: "",
    orcs: "Decatur",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.5575369574,
    cost: 0.5575369574
  },
  {
    rank: 27,
    teamNumber: 1557,
    school: "Harvard University A",
    tpr: 41,
    regional: "New Rochelle",
    orcs: "Chestnut Hill",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 18,
    extraBidsEarned: 0,
    winCSPoints: 8.5,
    tprPoints: 1.38531072,
    cost: 9.88531072
  },
  {
    rank: 28,
    teamNumber: 1358,
    school: "Hendrix College A",
    tpr: 2.5,
    regional: "Dallas",
    orcs: "Memphis",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 14,
    extraBidsEarned: 0,
    winCSPoints: 4.6875,
    tprPoints: 0.1294259494,
    cost: 4.816925949
  },
  {
    rank: 29,
    teamNumber: 1126,
    school: "Hillsdale College A",
    tpr: 20.25,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 17,
    extraBidsEarned: 0,
    winCSPoints: 6.1875,
    tprPoints: 0.8804666116,
    cost: 7.067966612
  },
  {
    rank: 30,
    teamNumber: 1127,
    school: "Hillsdale College B",
    tpr: 4.5,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 13,
    extraBidsEarned: 0,
    winCSPoints: 4.53125,
    tprPoints: 0.2287630513,
    cost: 4.760013051
  },
  {
    rank: 31,
    teamNumber: 1238,
    school: "Indiana University A",
    tpr: 39.92,
    regional: "St. Louis",
    orcs: "Geneva",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 12.5,
    extraBidsEarned: 0,
    winCSPoints: 7.125,
    tprPoints: 1.36895681,
    cost: 8.49395681
  },
  {
    rank: 32,
    teamNumber: 1239,
    school: "Indiana University B",
    tpr: 6.25,
    regional: "St. Louis",
    orcs: "Geneva",
    regionalWins: 5,
    regionalTies: 1,
    regionalCS: 15.5,
    extraBidsEarned: 0,
    winCSPoints: 5.4140625,
    tprPoints: 0.3126178484,
    cost: 5.726680348
  },
  {
    rank: 33,
    teamNumber: 1652,
    school: "Johns Hopkins University A",
    tpr: 18,
    regional: "",
    orcs: "Richmond",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.8015534477,
    cost: 0.8015534477
  },
  {
    rank: 34,
    teamNumber: 1020,
    school: "Juniata College A",
    tpr: 0,
    regional: "State College",
    orcs: "Central Islip",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 10.5,
    extraBidsEarned: 0,
    winCSPoints: 5.3828125,
    tprPoints: 0,
    cost: 5.3828125
  },
  {
    rank: 35,
    teamNumber: 1280,
    school: "Liberty University A",
    tpr: 0,
    regional: "Chapel Hill",
    orcs: "Richmond",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 7.75,
    tprPoints: 0,
    cost: 7.75
  },
  {
    rank: 36,
    teamNumber: 1421,
    school: "Loyola Marymount University A",
    tpr: 0,
    regional: "Claremont",
    orcs: "Santa Monica",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 14.5,
    extraBidsEarned: 0,
    winCSPoints: 6.1953125,
    tprPoints: 0,
    cost: 6.1953125
  },
  {
    rank: 37,
    teamNumber: 1011,
    school: "Loyola University-Chicago A",
    tpr: 18,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 19,
    extraBidsEarned: 0,
    winCSPoints: 6.5625,
    tprPoints: 0.8015534477,
    cost: 7.364053448
  },
  {
    rank: 38,
    teamNumber: 1021,
    school: "Miami University A",
    tpr: 56.67,
    regional: "",
    orcs: "Hamilton",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.5,
    cost: 1.5
  },
  {
    rank: 39,
    teamNumber: 1022,
    school: "Miami University B",
    tpr: 15,
    regional: "",
    orcs: "Hamilton",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.6889794948,
    cost: 0.6889794948
  },
  {
    rank: 40,
    teamNumber: 1510,
    school: "Michigan State University A",
    tpr: 10.5,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 16,
    extraBidsEarned: 0,
    winCSPoints: 7,
    tprPoints: 0.5043548492,
    cost: 7.504354849
  },
  {
    rank: 97,
    teamNumber: 1511,
    school: "Michigan State University B",
    tpr: 5,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 5,
    regionalTies: 1,
    regionalCS: 18.5,
    extraBidsEarned: 0,
    winCSPoints: 5.9296875,
    tprPoints: 0.2530134854,
    cost: 6.182700985
  },
  {
    rank: 41,
    teamNumber: 1318,
    school: "Moorpark College A",
    tpr: 0,
    regional: "Claremont",
    orcs: "Santa Monica",
    regionalWins: 5,
    regionalTies: 1,
    regionalCS: 16,
    extraBidsEarned: 0,
    winCSPoints: 5.5,
    tprPoints: 0,
    cost: 5.5
  },
  {
    rank: 42,
    teamNumber: 1506,
    school: "New York University A",
    tpr: 40.73,
    regional: "",
    orcs: "Central Islip",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.381324391,
    cost: 1.381324391
  },
  {
    rank: 43,
    teamNumber: 1077,
    school: "North Central College A",
    tpr: 8.75,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 15.5,
    extraBidsEarned: 0,
    winCSPoints: 6.890625,
    tprPoints: 0.4274477642,
    cost: 7.318072764
  },
  {
    rank: 44,
    teamNumber: 1693,
    school: "Northwestern University A",
    tpr: 35.58,
    regional: "Lawrence",
    orcs: "Cedar Rapids",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 7.75,
    tprPoints: 1.292251454,
    cost: 9.042251454
  },
  {
    rank: 45,
    teamNumber: 1694,
    school: "Northwestern University B",
    tpr: 18.5,
    regional: "Lawrence",
    orcs: "Cedar Rapids",
    regionalWins: 6,
    regionalTies: 2,
    regionalCS: 10.5,
    extraBidsEarned: 0,
    winCSPoints: 5.796875,
    tprPoints: 0.8194983953,
    cost: 6.616373395
  },
  {
    rank: 46,
    teamNumber: 1217,
    school: "Northwood University A",
    tpr: 23.25,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 21.5,
    extraBidsEarned: 0,
    winCSPoints: 7.03125,
    tprPoints: 0.9783277626,
    cost: 8.009577763
  },
  {
    rank: 47,
    teamNumber: 1218,
    school: "Northwood University B",
    tpr: 0,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 5,
    regionalTies: 1,
    regionalCS: 15.5,
    extraBidsEarned: 0,
    winCSPoints: 5.4140625,
    tprPoints: 0,
    cost: 5.4140625
  },
  {
    rank: 48,
    teamNumber: 1410,
    school: "Ohio State University A",
    tpr: 41.33,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 13.5,
    extraBidsEarned: 1,
    winCSPoints: 6.453125,
    tprPoints: 1.390090419,
    cost: 8.627536961
  },
  {
    rank: 49,
    teamNumber: 1411,
    school: "Ohio State University B",
    tpr: 17.25,
    regional: "Columbus",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 13,
    extraBidsEarned: 1,
    winCSPoints: 6.34375,
    tprPoints: 0.7741981453,
    cost: 7.82974296
  },
  {
    rank: 50,
    teamNumber: 1229,
    school: "Patrick Henry College A",
    tpr: 32.77,
    regional: "",
    orcs: "Hamilton",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.233203188,
    cost: 1.233203188
  },
  {
    rank: 51,
    teamNumber: 1230,
    school: "Patrick Henry College B",
    tpr: 15.5,
    regional: "",
    orcs: "Hamilton",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.7083256617,
    cost: 0.7083256617
  },
  {
    rank: 52,
    teamNumber: 1136,
    school: "Pennsylvania State University A",
    tpr: 27.75,
    regional: "State College",
    orcs: "Hamilton",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 7.75,
    tprPoints: 1.109355773,
    cost: 8.859355773
  },
  {
    rank: 53,
    teamNumber: 1137,
    school: "Pennsylvania State University B",
    tpr: 13.25,
    regional: "Columbus",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 17,
    extraBidsEarned: 0,
    winCSPoints: 7.21875,
    tprPoints: 0.6194288107,
    cost: 7.838178811
  },
  {
    rank: 54,
    teamNumber: 1122,
    school: "Quinnipiac University A",
    tpr: 5,
    regional: "New Haven",
    orcs: "Chestnut Hill",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 17.5,
    extraBidsEarned: 0,
    winCSPoints: 6.28125,
    tprPoints: 0.2530134854,
    cost: 6.534263485
  },
  {
    rank: 55,
    teamNumber: 1078,
    school: "Rhodes College A",
    tpr: 53.4,
    regional: "",
    orcs: "Memphis",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.495005634,
    cost: 1.495005634
  },
  {
    rank: 56,
    teamNumber: 1079,
    school: "Rhodes College B",
    tpr: 38.67,
    regional: "",
    orcs: "Memphis",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.348668323,
    cost: 1.348668323
  },
  {
    rank: 57,
    teamNumber: 1368,
    school: "Rice University A",
    tpr: 11.25,
    regional: "",
    orcs: "Memphis",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.5364392665,
    cost: 0.5364392665
  },
  {
    rank: 58,
    teamNumber: 1588,
    school: "Rutgers University A",
    tpr: 32.5,
    regional: "",
    orcs: "Richmond",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.227141093,
    cost: 1.227141093
  },
  {
    rank: 59,
    teamNumber: 1039,
    school: "Stanford University A",
    tpr: 44.16,
    regional: "",
    orcs: "Geneva",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.426903017,
    cost: 1.426903017
  },
  {
    rank: 60,
    teamNumber: 1262,
    school: "Tufts University A",
    tpr: 32.5,
    regional: "",
    orcs: "Chestnut Hill",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.227141093,
    cost: 1.227141093
  },
  {
    rank: 61,
    teamNumber: 1258,
    school: "University of California, Berkeley A",
    tpr: 34.07,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.261437756,
    cost: 1.261437756
  },
  {
    rank: 62,
    teamNumber: 1259,
    school: "University of California, Berkeley B",
    tpr: 21.3,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.9156743466,
    cost: 0.9156743466
  },
  {
    rank: 63,
    teamNumber: 1517,
    school: "University of California, Irvine A",
    tpr: 39.66,
    regional: "Claremont",
    orcs: "Santa Monica",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 14.5,
    extraBidsEarned: 1,
    winCSPoints: 6.671875,
    tprPoints: 1.364857029,
    cost: 8.840405232
  },
  {
    rank: 64,
    teamNumber: 1518,
    school: "University of California, Irvine B",
    tpr: 22.83,
    regional: "Claremont",
    orcs: "Santa Monica",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 18.5,
    extraBidsEarned: 1,
    winCSPoints: 6.46875,
    tprPoints: 0.9651333218,
    cost: 8.177271654
  },
  {
    rank: 65,
    teamNumber: 1492,
    school: "University of California, Los Angeles A",
    tpr: 45.33,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.439936458,
    cost: 1.439936458
  },
  {
    rank: 66,
    teamNumber: 1493,
    school: "University of California, Los Angeles B",
    tpr: 21,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.9057200852,
    cost: 0.9057200852
  },
  {
    rank: 67,
    teamNumber: 1679,
    school: "University of California, San Diego A",
    tpr: 18.16,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.8073212397,
    cost: 0.8073212397
  },
  {
    rank: 68,
    teamNumber: 1680,
    school: "University of California, San Diego B",
    tpr: 1,
    regional: "",
    orcs: "Santa Monica",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.05247098939,
    cost: 0.05247098939
  },
  {
    rank: 69,
    teamNumber: 1090,
    school: "University of Central Florida A",
    tpr: 11,
    regional: "",
    orcs: "Decatur",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.5258028449,
    cost: 0.5258028449
  },
  {
    rank: 70,
    teamNumber: 1028,
    school: "University of Central Missouri A",
    tpr: 16.25,
    regional: "Lawrence",
    orcs: "Cedar Rapids",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 16,
    extraBidsEarned: 0,
    winCSPoints: 6,
    tprPoints: 0.7369070309,
    cost: 6.736907031
  },
  {
    rank: 71,
    teamNumber: 1616,
    school: "University of Chicago A",
    tpr: 40.53,
    regional: "",
    orcs: "Geneva",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.37832765,
    cost: 1.37832765
  },
  {
    rank: 72,
    teamNumber: 1617,
    school: "University of Chicago B",
    tpr: 20.8,
    regional: "",
    orcs: "Geneva",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.8990372036,
    cost: 0.8990372036
  },
  {
    rank: 73,
    teamNumber: 1566,
    school: "University of Cincinnati A",
    tpr: 22.05,
    regional: "Cincinnati",
    orcs: "Geneva",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 17,
    extraBidsEarned: 0,
    winCSPoints: 7.21875,
    tprPoints: 0.94019218,
    cost: 8.15894218
  },
  {
    rank: 74,
    teamNumber: 1567,
    school: "University of Cincinnati B",
    tpr: 9.5,
    regional: "St. Louis",
    orcs: "Geneva",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 13,
    extraBidsEarned: 0,
    winCSPoints: 6.34375,
    tprPoints: 0.4607582483,
    cost: 6.804508248
  },
  {
    rank: 75,
    teamNumber: 1400,
    school: "University of Connecticut A",
    tpr: 10,
    regional: "New Rochelle",
    orcs: "Chestnut Hill",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 17.5,
    extraBidsEarned: 0,
    winCSPoints: 6.28125,
    tprPoints: 0.482673317,
    cost: 6.763923317
  },
  {
    rank: 76,
    teamNumber: 1401,
    school: "University of Connecticut B",
    tpr: 0,
    regional: "New Rochelle",
    orcs: "Chestnut Hill",
    regionalWins: 5,
    regionalTies: 2,
    regionalCS: 14.5,
    extraBidsEarned: 0,
    winCSPoints: 5.71875,
    tprPoints: 0,
    cost: 5.71875
  },
  {
    rank: 77,
    teamNumber: 1143,
    school: "University of Dayton A",
    tpr: 12.5,
    regional: "Cincinnati",
    orcs: "Hamilton",
    regionalWins: 5,
    regionalTies: 2,
    regionalCS: 16.5,
    extraBidsEarned: 0,
    winCSPoints: 6.09375,
    tprPoints: 0.5887456127,
    cost: 6.682495613
  },
  {
    rank: 78,
    teamNumber: 1144,
    school: "University of Dayton B",
    tpr: 0,
    regional: "Cincinnati",
    orcs: "Hamilton",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 4.84375,
    tprPoints: 0,
    cost: 4.84375
  },
  {
    rank: 79,
    teamNumber: 1117,
    school: "University of Florida A",
    tpr: 35,
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.280667668,
    cost: 1.280667668
  },
  {
    rank: 80,
    teamNumber: 1118,
    school: "University of Florida B",
    tpr: 25.5,
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.046206325,
    cost: 1.046206325
  },
  {
    rank: 81,
    teamNumber: 1553,
    school: "University of Georgia A",
    tpr: 25,
    regional: "Columbia",
    orcs: "Memphis",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 2,
    winCSPoints: 6.78125,
    tprPoints: 1.031530889,
    cost: 9.375337067
  },
  {
    rank: 82,
    teamNumber: 1554,
    school: "University of Georgia B",
    tpr: 13,
    regional: "Columbia",
    orcs: "Memphis",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 14,
    extraBidsEarned: 2,
    winCSPoints: 6.09375,
    tprPoints: 0.6092594622,
    cost: 8.043611355
  },
  {
    rank: 83,
    teamNumber: 1074,
    school: "University of Illinois A",
    tpr: 19,
    regional: "Lawrence",
    orcs: "Cedar Rapids",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 13,
    extraBidsEarned: 0,
    winCSPoints: 6.34375,
    tprPoints: 0.8372098063,
    cost: 7.180959806
  },
  {
    rank: 84,
    teamNumber: 1075,
    school: "University of Illinois B",
    tpr: 7.5,
    regional: "Lawrence",
    orcs: "Cedar Rapids",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 16,
    extraBidsEarned: 0,
    winCSPoints: 5,
    tprPoints: 0.370762608,
    cost: 5.370762608
  },
  {
    rank: 85,
    teamNumber: 1371,
    school: "University of Illinois, Chicago A",
    tpr: 13.5,
    regional: "Columbus",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 1,
    regionalCS: 14,
    extraBidsEarned: 0,
    winCSPoints: 7.03125,
    tprPoints: 0.6295397751,
    cost: 7.660789775
  },
  {
    rank: 86,
    teamNumber: 1396,
    school: "University of Iowa A",
    tpr: 23.43,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 14,
    extraBidsEarned: 0,
    winCSPoints: 6.5625,
    tprPoints: 0.983932079,
    cost: 7.546432079
  },
  {
    rank: 87,
    teamNumber: 1171,
    school: "University of Louisiana, Monroe A",
    tpr: 12.75,
    regional: "Dallas",
    orcs: "Memphis",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 14,
    extraBidsEarned: 0,
    winCSPoints: 6.5625,
    tprPoints: 0.5990317295,
    cost: 7.161531729
  },
  {
    rank: 88,
    teamNumber: 1172,
    school: "University of Louisiana, Monroe B",
    tpr: 0,
    regional: "Dallas",
    orcs: "Memphis",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 20,
    extraBidsEarned: 0,
    winCSPoints: 5.625,
    tprPoints: 0,
    cost: 5.625
  },
  {
    rank: 89,
    teamNumber: 1320,
    school: "University of Massachusetts, Amherst A",
    tpr: 4.5,
    regional: "",
    orcs: "Chestnut Hill",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.2287630513,
    cost: 0.2287630513
  },
  {
    rank: 90,
    teamNumber: 1170,
    school: "University of Massachusetts, Lowell A",
    tpr: 9.25,
    regional: "New Haven",
    orcs: "Chestnut Hill",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 6.78125,
    tprPoints: 0.4497131377,
    cost: 7.230963138
  },
  {
    rank: 91,
    teamNumber: 1224,
    school: "University of Michigan A",
    tpr: 47.07,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 1,
    regionalCS: 17,
    extraBidsEarned: 1,
    winCSPoints: 7.734375,
    tprPoints: 1.456954545,
    cost: 10.1104625
  },
  {
    rank: 92,
    teamNumber: 1225,
    school: "University of Michigan B",
    tpr: 25.05,
    regional: "Ypsilanti",
    orcs: "Hamilton",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 11,
    extraBidsEarned: 1,
    winCSPoints: 5.90625,
    tprPoints: 1.033008942,
    cost: 7.633184836
  },
  {
    rank: 93,
    teamNumber: 1458,
    school: "University of Nebraska A",
    tpr: 0,
    regional: "Lawrence",
    orcs: "Cedar Rapids",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 19.5,
    extraBidsEarned: 0,
    winCSPoints: 6.65625,
    tprPoints: 0,
    cost: 6.65625
  },
  {
    rank: 94,
    teamNumber: 1524,
    school: "University of North Carolina A",
    tpr: 17.25,
    regional: "",
    orcs: "Richmond",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0.7741981453,
    cost: 0.7741981453
  },
  {
    rank: 95,
    teamNumber: 1198,
    school: "University of Notre Dame A",
    tpr: 18.75,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 18,
    extraBidsEarned: 0,
    winCSPoints: 6.375,
    tprPoints: 0.8283832929,
    cost: 7.203383293
  },
  {
    rank: 96,
    teamNumber: 1668,
    school: "University of Richmond A",
    tpr: 28.5,
    regional: "",
    orcs: "Central Islip",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.129354674,
    cost: 1.129354674
  },
  {
    rank: 98,
    teamNumber: 1178,
    school: "University of Scranton A",
    tpr: 0,
    regional: "State College",
    orcs: "Central Islip",
    regionalWins: 5,
    regionalTies: 1,
    regionalCS: 17,
    extraBidsEarned: 0,
    winCSPoints: 5.671875,
    tprPoints: 0,
    cost: 5.671875
  },
  {
    rank: 99,
    teamNumber: 1333,
    school: "University of South Dakota A",
    tpr: 11,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 12.5,
    extraBidsEarned: 0,
    winCSPoints: 4.453125,
    tprPoints: 0.5258028449,
    cost: 4.978927845
  },
  {
    rank: 100,
    teamNumber: 1633,
    school: "University of Southern California A",
    tpr: 20.05,
    regional: "Tempe",
    orcs: "Santa Monica",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 13.5,
    extraBidsEarned: 1,
    winCSPoints: 6.453125,
    tprPoints: 0.8736436081,
    cost: 8.059445469
  },
  {
    rank: 101,
    teamNumber: 1634,
    school: "University of Southern California B",
    tpr: 11.75,
    regional: "Tempe",
    orcs: "Santa Monica",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 14.5,
    extraBidsEarned: 1,
    winCSPoints: 6.1953125,
    tprPoints: 0.5575369574,
    cost: 7.428134403
  },
  {
    rank: 102,
    teamNumber: 1219,
    school: "University of Vermont A",
    tpr: 7.5,
    regional: "New Haven",
    orcs: "Chestnut Hill",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 21.5,
    extraBidsEarned: 0,
    winCSPoints: 5.859375,
    tprPoints: 0.370762608,
    cost: 6.230137608
  },
  {
    rank: 103,
    teamNumber: 1001,
    school: "University of Virginia A",
    tpr: 55.6,
    regional: "Williamsburg",
    orcs: "Richmond",
    regionalWins: 8,
    regionalTies: 0,
    regionalCS: 18,
    extraBidsEarned: 0,
    winCSPoints: 8.5,
    tprPoints: 1.499465248,
    cost: 9.999465248
  },
  {
    rank: 104,
    teamNumber: 1002,
    school: "University of Virginia B",
    tpr: 30,
    regional: "Williamsburg",
    orcs: "Richmond",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 15,
    extraBidsEarned: 0,
    winCSPoints: 5.8125,
    tprPoints: 1.167776105,
    cost: 6.980276105
  },
  {
    rank: 105,
    teamNumber: 1450,
    school: "University of Wisconsin, Madison A",
    tpr: 7.5,
    regional: "St. Louis",
    orcs: "Geneva",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 16.5,
    extraBidsEarned: 0,
    winCSPoints: 5.078125,
    tprPoints: 0.370762608,
    cost: 5.448887608
  },
  {
    rank: 106,
    teamNumber: 1123,
    school: "Washington University in St. Louis A",
    tpr: 28.7,
    regional: "Topeka",
    orcs: "Cedar Rapids",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 18,
    extraBidsEarned: 0,
    winCSPoints: 6.375,
    tprPoints: 1.134598971,
    cost: 7.509598971
  },
  {
    rank: 107,
    teamNumber: 1124,
    school: "Washington University in St. Louis B",
    tpr: 0,
    regional: "St. Louis",
    orcs: "Cedar Rapids",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 17.5,
    extraBidsEarned: 0,
    winCSPoints: 5.234375,
    tprPoints: 0,
    cost: 5.234375
  },
  {
    rank: 108,
    teamNumber: 1195,
    school: "Wellesley College A",
    tpr: 13,
    regional: "New Rochelle",
    orcs: "Chestnut Hill",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 16.5,
    extraBidsEarned: 0,
    winCSPoints: 5.078125,
    tprPoints: 0.6092594622,
    cost: 5.687384462
  },
  {
    rank: 109,
    teamNumber: 1540,
    school: "Wesleyan University A",
    tpr: 24.5,
    regional: "",
    orcs: "Chestnut Hill",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.016621916,
    cost: 1.016621916
  },
  {
    rank: 110,
    teamNumber: 1016,
    school: "Wheaton College A",
    tpr: 26.63,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 7,
    regionalTies: 0,
    regionalCS: 19,
    extraBidsEarned: 0,
    winCSPoints: 7.65625,
    tprPoints: 1.078512509,
    cost: 8.734762509
  },
  {
    rank: 114,
    teamNumber: 1017,
    school: "Wheaton College B",
    tpr: 2.5,
    regional: "Wheaton",
    orcs: "Geneva",
    regionalWins: 6,
    regionalTies: 1,
    regionalCS: 11,
    extraBidsEarned: 0,
    winCSPoints: 5.484375,
    tprPoints: 0.1294259494,
    cost: 5.613800949
  },
  {
    rank: 111,
    teamNumber: 1597,
    school: "Williams College A",
    tpr: 1.5,
    regional: "New Rochelle",
    orcs: "Chestnut Hill",
    regionalWins: 5,
    regionalTies: 0,
    regionalCS: 18.5,
    extraBidsEarned: 0,
    winCSPoints: 5.390625,
    tprPoints: 0.07835617928,
    cost: 5.468981179
  },
  {
    rank: 112,
    teamNumber: 1242,
    school: "Xavier University A",
    tpr: 21,
    regional: "Cincinnati",
    orcs: "Hamilton",
    regionalWins: 6,
    regionalTies: 0,
    regionalCS: 19.5,
    extraBidsEarned: 0,
    winCSPoints: 6.65625,
    tprPoints: 0.9057200852,
    cost: 7.561970085
  },
  {
    rank: 113,
    teamNumber: 1577,
    school: "Yale University A",
    tpr: 56.67,
    regional: "",
    orcs: "Chestnut Hill",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 1.5,
    cost: 1.5
  },
  {
    rank: 115,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 116,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 117,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 118,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 119,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 120,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 121,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 122,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 123,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 124,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 125,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 126,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 127,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 128,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 129,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 130,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 131,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 132,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 133,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 134,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 135,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 136,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 137,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 138,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 139,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 140,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 141,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 142,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 143,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 144,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 145,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 146,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 147,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 148,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 149,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 150,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 151,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 152,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 153,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 154,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 155,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 156,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 157,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 158,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 159,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 160,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 161,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 162,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 163,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 164,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 165,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 166,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 167,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 168,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 169,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 170,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 171,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 172,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 173,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 174,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 175,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 176,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 177,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 178,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 179,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 180,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 181,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 182,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 183,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 184,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 185,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 186,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 187,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 188,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 189,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 190,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 191,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 192,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: 0,
    tprPoints: 0,
    cost: 0
  },
  {
    rank: 193,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 194,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 195,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 196,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 197,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 198,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 199,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 200,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 201,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 202,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 203,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 204,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 205,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 206,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 207,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 208,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 209,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 210,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 211,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 212,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 213,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 214,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 215,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  },
  {
    rank: 216,
    teamNumber: "",
    school: "#N/A",
    tpr: "",
    regional: "",
    orcs: "",
    regionalWins: "",
    regionalTies: "",
    regionalCS: "",
    extraBidsEarned: "",
    winCSPoints: "",
    tprPoints: 0,
    cost: ""
  }
];

var selectOptions = "";
for (var a = 0; a < data.length; a++) {
  selectOptions +=
    "<option>" + data[a].teamNumber + " " + data[a].school + "</option>\n";
}

$(document).ready(function() {
  for (var a = 0; a < 8; a++) {
    $("#select" + a).append(selectOptions);
  }
});

$(".teamSelect").on("change", function() {
  //Get team number
  var row = this.id.substring(6, 7);
  var team = this.value.substring(0, 4);
  var teamIndex = 0;

  //Determine team's index in the data array
  for (var a = 0; a < data.length; a++) {
    if (team == data[a].teamNumber) {
      teamIndex = a;
      a = data.length;
    }
  }

  //Set the teams division
  $("#division" + row).html(data[teamIndex].orcs);

  //Determine whether cost should be raw cost or holdover cost
  var cost;
  if ($("#orcs" + row).prop("checked")) {
    cost = data[teamIndex].holdoverCost;
  } else {
    cost = data[teamIndex].nctCost;
  }
  $("#cost" + row).html(cost);

  validateDivision();
  validateCost();
});

$(".check").on("click", function() {
  //Find team number of the team in question
  var row = this.id.substring(4, 5);
  var team = $("#select" + row)
    .val()
    .substring(0, 4);

  //Determine that team's index in the data array
  for (var a = 0; a < data.length; a++) {
    if (team == data[a].teamNumber) {
      teamIndex = a;
      a = data.length;
    }
  }

  //Set the cost of the team based on whether holdover or not
  if ($(this).prop("checked")) {
    var newValue = data[teamIndex].holdoverCost;
  } else {
    var newValue = data[teamIndex].nctCost;
  }
  $("#cost" + row).html(newValue);
});

$("#button").click(function() {
  var division = validateDivision();
  var cost = validateCost();
  if (division && cost) {
    var postData = {
      name: $("#teamName").val(),
      email: $("#email").val(),
      team0: $("#select0")
        .val()
        .substring(0, 4),
      team1: $("#select1")
        .val()
        .substring(0, 4),
      team2: $("#select2")
        .val()
        .substring(0, 4),
      team3: $("#select3")
        .val()
        .substring(0, 4),
      team4: $("#select4")
        .val()
        .substring(0, 4),
      team5: $("#select5")
        .val()
        .substring(0, 4),
      team6: $("#select6")
        .val()
        .substring(0, 4),
      team7: $("#select7")
        .val()
        .substring(0, 4)
    };

    $.ajax({
      type: "POST",
      url: "./submit.php",
      data: postData,
      success: function(response) {
        if ((response = 0)) {
          alert("Team submitted successfully");
        } else {
          alert("There was an error processing your team");
        }
      }
    });
  } else {
    alert(
      "You have selected too many teams from the same division, exceeded the maximum cost, \n\
or provided an improper email/Perjuries username"
    );
  }
});

function validateDivision() {
  var divisionList = [0, 0];
  for (var a = 0; a < 8; a++) {
    if ($("#division" + a).html() == "Cedar Rapids") {
      divisionList[0]++;
    } else if ($("#division" + a).html() == "Hamilton") {
      divisionList[1]++;
    }
  }
  if (divisionList[0] != 4 || divisionList[1] != 4) {
    $("#divisionValidator").html("🔴");
    return false;
  } else {
    $("#divisionValidator").html("🔵");
    return true;
  }
}

function validateCost() {
  var maxCost = 200.0;
  var totalCost = 0.0;
  for (var a = 0; a < 8; a++) {
    var teamCost = Number($("#cost" + a).html());
    totalCost += teamCost;
  }
  $("#totalCost").html(totalCost);
  if (totalCost > maxCost) {
    return false;
  } else {
    return true;
  }
}

function containsDuplicates(array) {
  var counts = [];
  for (var i = 0; i <= array.length; i++) {
    if (counts[array[i]] === undefined) {
      counts[array[i]] = 1;
    } else {
      return true;
    }
  }
  return false;
}
